USE [master]
GO
/****** Object:  Database [QL_BanHang]    Script Date: 6/22/2021 10:25:04 AM ******/
CREATE DATABASE [QL_BanHang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QL_BanHang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QL_BanHang.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QL_BanHang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QL_BanHang_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QL_BanHang] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QL_BanHang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QL_BanHang] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QL_BanHang] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QL_BanHang] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QL_BanHang] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QL_BanHang] SET ARITHABORT OFF 
GO
ALTER DATABASE [QL_BanHang] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QL_BanHang] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QL_BanHang] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QL_BanHang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QL_BanHang] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QL_BanHang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QL_BanHang] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QL_BanHang] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QL_BanHang] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QL_BanHang] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QL_BanHang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QL_BanHang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QL_BanHang] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QL_BanHang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QL_BanHang] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QL_BanHang] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QL_BanHang] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QL_BanHang] SET RECOVERY FULL 
GO
ALTER DATABASE [QL_BanHang] SET  MULTI_USER 
GO
ALTER DATABASE [QL_BanHang] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QL_BanHang] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QL_BanHang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QL_BanHang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QL_BanHang] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QL_BanHang] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QL_BanHang', N'ON'
GO
ALTER DATABASE [QL_BanHang] SET QUERY_STORE = OFF
GO
USE [QL_BanHang]
GO
/****** Object:  Table [dbo].[tb_CTHD]    Script Date: 6/22/2021 10:25:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CTHD](
	[MaHD] [varchar](10) NOT NULL,
	[MaHH] [varchar](10) NOT NULL,
	[DonGia] [varchar](20) NULL,
	[SoLuong] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHD] ASC,
	[MaHH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_HangHoa]    Script Date: 6/22/2021 10:25:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_HangHoa](
	[MaHang] [varchar](10) NOT NULL,
	[TenHang] [nvarchar](50) NULL,
	[DonGia] [varchar](20) NULL,
	[SoLuong] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_HoaDon]    Script Date: 6/22/2021 10:25:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_HoaDon](
	[MaHoaDon] [varchar](10) NOT NULL,
	[KhachHang] [nvarchar](50) NULL,
	[NhanVienLap] [nvarchar](50) NULL,
	[NgayLap] [date] NULL,
	[MaKH] [varchar](10) NULL,
	[MaNV] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_KhachHang]    Script Date: 6/22/2021 10:25:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_KhachHang](
	[MaKH] [varchar](10) NOT NULL,
	[TenKH] [nvarchar](50) NULL,
	[SDT] [varchar](10) NULL,
	[GioiTinh] [nvarchar](5) NULL,
	[DiaChi] [nvarchar](50) NULL,
	[Namsinh] [datetime] NULL,
	[Emails] [varchar](200) NULL,
	[SoDiem] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_NhanVien]    Script Date: 6/22/2021 10:25:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_NhanVien](
	[MaNV] [varchar](10) NOT NULL,
	[TenNhanVien] [nvarchar](50) NULL,
	[Gioitinh] [nvarchar](5) NULL,
	[NamSinh] [date] NULL,
	[DiaChi] [nvarchar](50) NULL,
	[SDT] [varchar](11) NULL,
	[MatKhau] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tb_CTHD]  WITH CHECK ADD FOREIGN KEY([MaHD])
REFERENCES [dbo].[tb_HoaDon] ([MaHoaDon])
GO
ALTER TABLE [dbo].[tb_CTHD]  WITH CHECK ADD FOREIGN KEY([MaHH])
REFERENCES [dbo].[tb_HangHoa] ([MaHang])
GO
ALTER TABLE [dbo].[tb_HoaDon]  WITH CHECK ADD FOREIGN KEY([MaKH])
REFERENCES [dbo].[tb_KhachHang] ([MaKH])
GO
ALTER TABLE [dbo].[tb_HoaDon]  WITH CHECK ADD FOREIGN KEY([MaNV])
REFERENCES [dbo].[tb_NhanVien] ([MaNV])
GO
USE [master]
GO
ALTER DATABASE [QL_BanHang] SET  READ_WRITE 
GO
